"""Fix permissions

Revision ID: 40a64b82a062
Revises: 
Create Date: 2025-02-07 06:43:17.947501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a64b82a062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_list', schema=None) as batch_op:
        batch_op.drop_constraint('review_list_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('study_notes', schema=None) as batch_op:
        batch_op.drop_constraint('study_notes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_constraint('study_plans_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('study_records_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_records_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_plans_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_notes_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_list_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
